### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by shgubar** [njh/perl-websphere-mqtt-client#1]
How to use authentication with module? 
Where and how I can use username and password (my MQTT Server using authentication)?

**Comment by njh** [comment]
This library is very old and I believe only implements MQTT protocol v3, which did not have support for authentication.

It is probably better to try something a little bit newer. I have not tried Net::MQTT, but it is probably worth a look:
http://search.cpan.org/dist/Net-MQTT/
